=== aspectran-projects/aspectran/aspectran-web/config/aspectran/dtd/aspectran-1.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT aspectran (settings? | typeAliases* | import* | bean* | translet* | aspect*)*>
<!ATTLIST aspectran
namespace CDATA #IMPLIED
>

<!ELEMENT settings (setting*)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | reference | null)*>
<!ATTLIST item
name CDATA #IMPLIED
value CDATA #IMPLIED
type CDATA #IMPLIED
valueType CDATA #IMPLIED
defaultValue CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA | reference | null)*>
<!ATTLIST value
name CDATA #IMPLIED
tokenize (true | false) #IMPLIED
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
bean CDATA #IMPLIED
parameter CDATA #IMPLIED
attribute CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>

<!ELEMENT properties (item*)>

<!ELEMENT arguments (item*)>

<!ELEMENT parameters (item*)>

<!ELEMENT null EMPTY>

<!ELEMENT aspect (joinpoint?, default?, action*, before?, after?, around?, finally?, exceptionRaized?)>
<!ATTLIST aspect
id ID #IMPLIED
>

<!ELEMENT joinpoint (pointcut*)>
<!ATTLIST joinpoint
target (request | response | translet | action | scheduler | bean) #REQUIRED
>

<!ELEMENT pointcut (#PCDATA)>
<!ATTLIST pointcut
pattern CDATA #IMPLIED
>

<!ELEMENT default (settings)>
<!ELEMENT before (echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT after (echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT around (echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT finally (echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT exceptionRaized (echo? | action? | transform? | dispatch? | redirect? | forward?)*>

<!ELEMENT bean (features?, constructor?, properties*)>
<!ATTLIST bean
id ID #REQUIRED
class CDATA #IMPLIED
scope (singleton | prototype | request | session | application) #IMPLIED
factoryMethod CDATA #IMPLIED
initMethod CDATA #IMPLIED
destoryMethod CDATA #IMPLIED
lazyInit (true | false) #IMPLIED
parent CDATA #IMPLIED
>

<!ELEMENT features (class?, scope?, factoryMethod?, initMethod?, destroyMethod?, lazyInit?)>

<!ELEMENT class (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT factoryMethod (#PCDATA)>
<!ELEMENT initMethod (#PCDATA)>
<!ELEMENT destroyMethod (#PCDATA)>
<!ELEMENT lazyInit (#PCDATA)>

<!ELEMENT constructor (arguments?)>

<!ELEMENT translet (request?, contents?, response?, transform?, dispatch?, redirect?, forward?, exception?)>
<!ATTLIST translet
name CDATA #REQUIRED
hidden (true | false) #IMPLIED
extends CDATA #IMPLIED
>

<!ELEMENT request (attributes?, multiparts?)>
<!ATTLIST request
method CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>

<!ELEMENT multiparts (fileItem*)>

<!ELEMENT fileItem (allowFileExtentions? | denyFileExtentions?)>
<!ATTLIST fileItem
name CDATA #REQUIRED
>

<!ELEMENT allowFileExtentions (#PCDATA)>
<!ELEMENT denyFileExtentions (#PCDATA)>

<!ELEMENT contents (content*)>

<!ELEMENT content (echo? | action? | include?)*>
<!ATTLIST content
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | item | value | null)*>
<!ATTLIST echo
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
id CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT include (attributes?)>
<!ATTLIST include
id CDATA #IMPLIED
translet CDATA #REQUIRED
hidden (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST response
characterEncoding CDATA #IMPLIED
default CDATA #IMPLIED
>
<!ELEMENT exception (responseByContentType?, defaultResponse?)>

<!ELEMENT responseByContentType (transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT defaultResponse (transform? | dispatch? | redirect? | forward?)>

<!ELEMENT transform (echo | action | include | template)*>
<!ATTLIST transform
id CDATA #IMPLIED
type CDATA #REQUIRED
contentType CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
encoding CDATA #IMPLIED
noCache (true | false) #IMPLIED
>

<!ELEMENT dispatch (echo? | action? | include? | template)*>
<!ATTLIST dispatch
id CDATA #IMPLIED
contentType CDATA #IMPLIED
>

<!ELEMENT redirect (echo* | action* | include* | url? | parameters*)>
<!ATTLIST redirect
id CDATA #IMPLIED
contentType CDATA #IMPLIED
url CDATA #IMPLIED
translet CDATA #IMPLIED
excludeNullParameters CDATA #IMPLIED
>
<!ELEMENT url (#PCDATA)>

<!ELEMENT forward (echo* | action* | include* | parameters*)>
<!ATTLIST forward
id CDATA #IMPLIED
contentType CDATA #IMPLIED
translet CDATA #IMPLIED
>

=== aspectran-projects/aspectran/aspectran-web/config/aspectran/example-aspectran.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "./dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePattern" value="/example/*"/>
		<setting name="transletInterfaceClass" value="com.aspectran.web.activity.WebTranslet"/>
		<setting name="transletImplementClass" value="com.aspectran.web.activity.WebTransletImpl"/>
		<setting name="activityDefaultHandler" value="webActivityDefaultHandler"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
	</settings>
	
	<import resource="aspectran/example-scheduler-aspectran.xml"/>
	
	<bean id="webActivityDefaultHandler" class="com.aspectran.web.activity.WebActivityDefaultHandler" scope="singleton"/>
	<bean id="jspViewDispatcher" class="com.aspectran.web.view.JspViewDispatcher" scope="singleton"/>
	<bean id="example.*" class="com.aspectran.example.**.*Action" scope="singleton"/>
	<bean id="advice.*" class="com.aspectran.example.aspect.**.*Advice" scope="session"/>
	<bean id="sampleBean" class="com.aspectran.example.bean.SampleBean" scope="singleton"/>
	
	<aspect id="defaultRequestRule">
		<joinpoint scope="request"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="multipart.maxRequestSize" value="10M"/>
			<setting name="multipart.temporaryFilePath" value="/d:/"/>
		</settings>
	</aspect>
	
	<aspect id="defaultResponseRule">
		<joinpoint scope="response"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="defaultContentType" value="text/html"/>
			<setting name="viewDispatcher" value="jspViewDispatcher"/>
		</settings>
	</aspect>

	<aspect id="exception1">
		<joinpoint scope="translet">
			<pointcut>
				<within translet="/example/hello/*"/>
			</pointcut>
		</joinpoint>
		<advice>
			<exceptionRaized>
				<responseByContentType exceptionType="java.lang.reflect.InvocationTargetException">
					<transform contentType="text/xml" type="transform/xml">
						<echo>
							<item type="map">
								<value name="errorCode">E0001</value>
								<value name="message">error occured.</value>
							</item>
						</echo>
					</transform>
				</responseByContentType>
			</exceptionRaized>
		</advice>
	</aspect>

	<aspect id="helloAdvice">
		<joinpoint scope="content">
			<pointcut>
				<within>/example/hello/*@example.hello.HelloAction^applyTheAdvice</within>
				<within translet="/example/hello/*" bean="example.hello.HelloAction" method="applyTheAdvice"/>
			</pointcut>
		</joinpoint>
		<advice bean="advice.HelloAdvice">
			<before>
				<action method="beforeCountTo10"/>
			</before>
			<after>
				<action method="afterCountTo10"/>
			</after>
		</advice>
	</aspect>

	<translet name="/hello">
		<transform type="transform/text">
			<template>
				hello~ ${name}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10">
		<transform type="transform/text">
			<action id="result1" bean="example.hello.HelloAction" method="countTo10"/>
			<template>
@{result1}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10twice">
		<action id="result1" bean="example.hello.HelloAction" method="countTo10"/>
		<action id="result2" bean="example.hello.HelloAction" method="countTo10"/>
		<transform type="transform/text">
			<template>
(first)
@{result1}
(second)
@{result2}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10.xml">
		<transform type="transform/xml">
			<action id="result" bean="example.hello.HelloAction" method="countTo10AsArray"/>
		</transform>
	</translet>

	<translet name="hello/countTo10ext">
		<response>
			<transform type="transform/text">
				<action id="result" bean="example.hello.HelloAction" method="countTo10"/>
				<template>
					@{result}
				</template>
			</transform>
		</response>
		<response name=".xml">
			<transform type="transform/xml">
				<action bean="example.hello.HelloAction" method="countTo10AsArray"/>
			</transform>
		</response>
	</translet>

	<translet name="hello/applyTheAdvice.xml">
		<transform type="transform/xml">
			<action id="applyTheAdvice" bean="example.hello.HelloAction" method="applyTheAdvice"/>
		</transform>
	</translet>

	<translet name="echo">
		<transform type="transform/text" contentType="text/html">
			<echo id="echo">
				<item name="map0" type="map" valueType="string">
					<value name="item1">${item1:default1}</value>
					<value name="item2">${item2:default2}</value>
				</item>
			</echo>
			<template>
<![CDATA[
<html>
<body>
	<dl>
		<dt>item1</dt>
		<dd>@{echo^map0.item1}</dd>
		<dt>item2</dt>
		<dd>@{echo^map0.item2}</dd>
	</ul>
</body>
</html>
]]>
			</template>
		</transform>
	</translet>

	<translet name="hello/sampleBean.xml">
		<transform type="transform/text">
			<action bean="sampleBean" method="hello"/>
		</transform>
	</translet>

	<translet name="goNaver">
		<redirect url="http://www.naver.com"/>
	</translet>
	
</aspectran>

=== aspectran-projects/aspectran/aspectran-web/config/aspectran/aspectran.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "./dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePatternPrefix" value="test"/>
		<setting name="transletNamePatternSuffix" value=".do"/>
		<setting name="transletNamePattern" value="/test/*.do"/>
		<setting name="transletInterfaceClass" value="com.aspectran.web.activity.WebTranslet"/>
		<setting name="transletIntanceClass" value="com.aspectran.web.activity.AspectranWebTranslet"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
		<setting name="multipleTransletEnable" value="true"/>
	</settings>
	
	<aspect id="defaultRequestRule">
		<joinpoint target="translet" scope="request"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="multipart.maxRequestSize" value="10M"/>
			<setting name="multipart.temporaryFilePath" value="/d:/"/>
		</settings>
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</after>
	</aspect>
	
	<aspect id="frontRequestRule">
		<joinpoint target="translet" scope="request">
			<pointcut>front/*</pointcut>
		</joinpoint>
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</after>
	</aspect>

	<bean id="jspViewDispatcher" class="com.aspectran.web.view.JspViewDispatcher" scope="singleton"/>

	<aspect id="defaultResponseRule">
		<joinpoint target="translet" scope="response"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="defaultContentType" value="text/html"/>
			<setting name="viewDispatcher" value="jspViewDispatcher"/>
		</settings>
	</aspect>

	<aspect id="error">
		<joinpoint target="translet"/>
		<exceptionRaized>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
			<responseByContentType exceptionType="com.aspectran.test.web.LoginFailedException">
				<dispatch contentType="text/html">
					<template file="/WEB-INF/jsp/login.jsp"/>
				</dispatch>
				<transform contentType="text/plain" type="transform/json">
					<template>{}</template>
				</transform>
			</responseByContentType>
			<responseByContentType>
				<dispatch contentType="text/html">
					<template file="/WEB-INF/jsp/error.jsp"/>
				</dispatch>
				<!-- forward contentType="text/html" translet="error"/ -->
				<transform contentType="text/plain" type="transform/text">
					<template>
						오류 발생!
						오류 발생!
					</template>
				</transform>
				<transform contentType="text/xml" type="transform/xml">
					<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
						<properties>
							<item name="variable1">error</item>
							<item name="variable2">0001</item>
						</properties>
					</action>
					<echo id="error3">
						<item name="code">0002</item>
						<item name="message">오류 발생!</item>
					</echo>
					<echo id="error1">
						<item type="map">
							<value name="code">0001</value>
							<value name="message">오류 발생!</value>
						</item>
					</echo>
					<echo id="error2">
						<item type="map">
							<value name="code">0002</value>
							<value name="message">오류 발생!</value>
						</item>
						<item type="map">
							<value name="code">0004</value>
							<value name="message">오류 발생!</value>
						</item>
					</echo>
				</transform>
			</responseByContentType>
			<defaultResponse>
				<redirect translet="error"/>
			</defaultResponse>
		</exceptionRaized>
	</aspect>

	<aspect id="bean1">
		<joinpoint>
			<pointcut>front/*</pointcut>
		</joinpoint>
		<around>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</around>
	</aspect>

	<!--
		before: access logging
		after: error logging 
	-->
	<aspect id="logging">
		<joinpoint target="translet">
			<pointcut>front.action1</pointcut>
		</joinpoint>
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</after>
	</aspect>

	<!--
		scheduler
	-->
	<aspect id="scheduler1">
		<joinpoint target="scheduler">
			<pointcut type="interval">* * 10 0</pointcut>
		</joinpoint>
		<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
			<properties>
				<item name="variable1">error</item>
				<item name="variable2">0001</item>
			</properties>
		</action>
		<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
			<properties>
				<item name="variable1">error</item>
				<item name="variable2">0001</item>
			</properties>
		</action>
	</aspect>

	<!--
		Matching targets:
			request: reserved
			response: reserved
			bean: each time it is called
			translet: each time it is called
			action: each time it is called
		getAspectObject:
			a return object of <before> action.
	-->
	<aspect id="sqlmap">																																			
		<joinpoint target="translet" scope="content">
			<pointcut>
				front/a/*
				exclude(front/a/A*)
			</pointcut>
		</joinpoint>
		<before>
			<action bean="com.aspectran.support.orm.ibatis.AspectSqlMapClient" method="begin"/>
		</before>
		<finally>
			<action bean="com.aspectran.support.orm.ibatis.AspectSqlMapClient" method="end"/>
		</finally>
	</aspect>
	
	<bean id="aaa" class="com.aspectran.test.**.Sample*Test*Bean" scope="singleton"/>

	<import resource="front-translets.xml"/>
	<import resource="ajax-translets.xml"/>
	
</aspectran>

=== aspectran-projects/aspectran/aspectran-web/config/aspectran/aspectran-example.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "./dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePattern" value="/example/*"/>
		<setting name="transletInterfaceClass" value="com.aspectran.web.activity.WebTranslet"/>
		<setting name="transletImplementClass" value="com.aspectran.web.activity.AspectranWebTranslet"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
	</settings>
	
	<aspect id="defaultRequestRule">
		<joinpoint target="translet" scope="request"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="multipart.maxRequestSize" value="10M"/>
			<setting name="multipart.temporaryFilePath" value="/d:/"/>
		</settings>
	</aspect>
	
	<bean id="jspViewDispatcher" class="com.aspectran.web.view.JspViewDispatcher" scope="singleton"/>

	<aspect id="defaultResponseRule">
		<joinpoint target="translet" scope="response"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="defaultContentType" value="text/html"/>
			<setting name="viewDispatcher" value="jspViewDispatcher"/>
		</settings>
	</aspect>

	<aspect id="helloAdvice">
		<joinpoint target="translet" scope="action">
			<pointcut>/example/hello/*@applyTheAdvice</pointcut>
		</joinpoint>
		<before>
			<action bean="advice.HelloAdvice" method="beforeCountTo10"/>
		</before>
		<after>
			<action bean="advice.HelloAdvice" method="afterCountTo10"/>
		</after>
	</aspect>
	
	<bean id="example.*" class="com.aspectran.example.**.*Action" scope="singleton"/>
	<bean id="advice.*" class="com.aspectran.example.aspect.**.*Advice" scope="singleton"/>

	<translet name="hello">
		<transform type="transform/text">
			<template>
				hello~ ${name}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10">
		<transform type="transform/text">
			<action id="result" bean="example.hello.HelloAction" method="countTo10"/>
			<template>
				@{result}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10.xml">
		<transform type="transform/xml">
			<action id="result" bean="example.hello.HelloAction" method="countTo10AsArray"/>
		</transform>
	</translet>

	<translet name="hello/countTo10ext">
		<response>
			<transform type="transform/text">
				<action id="result" bean="example.hello.HelloAction" method="countTo10"/>
				<template>
					@{result}
				</template>
			</transform>
		</response>
		<response name=".xml">
			<transform type="transform/xml">
				<action id="result" bean="example.hello.HelloAction" method="countTo10AsArray"/>
			</transform>
		</response>
	</translet>

	<translet name="hello/applyTheAdvice.xml">
		<transform type="transform/xml">
			<action id="applyTheAdvice" bean="example.hello.HelloAction" method="applyTheAdvice"/>
		</transform>
	</translet>

	<translet name="goNaver">
		<redirect url="http://www.naver.com"/>
	</translet>
	
</aspectran>
