=== aspectran-projects/aspectran/trunk/aspectran-main/java/com/aspectran/base/context/builder/xml/dtd/translets-1.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT translets (settings?, serviceRule?, ticketRule?, requestRule?, responseRule?, exceptionRule?, typeAliases*, import*, use?, translet*)>
<!ATTLIST translets
namespace CDATA #IMPLIED
>

<!ELEMENT settings (setting*)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value (true | false) #REQUIRED
>

<!ELEMENT serviceRule (requestUriPattern, description?)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT requestUriPattern (#PCDATA | prefix | suffix)*>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>

<!ELEMENT ticketRule (checkcase*)>
<!ELEMENT checkcase (action, responseByContentType?, defaultResponse?)>
<!ATTLIST checkcase
id CDATA #REQUIRED
rejectInvalidTicket (true | false) "true"
checkpoint (request | response) "request"
>

<!ELEMENT ticket (arguments?, properties?)>
<!ATTLIST ticket
checkcase CDATA #REQUIRED
rejectInvalidTicket (true | false) "false"
checkpoint (request | response) "request"
>

<!ELEMENT requestRule (characterEncoding | multipart? | ticket*)*>

<!ELEMENT characterEncoding (#PCDATA)>

<!ELEMENT multipart (maxRequestSize, temporaryFilePath)>
<!ELEMENT maxRequestSize (#PCDATA)>
<!ELEMENT temporaryFilePath (#PCDATA)>

<!ELEMENT responseRule (characterEncoding | enforceResponseById? | ticket*)*>
<!ELEMENT enforceResponseById (#PCDATA)>

<!ELEMENT exceptionRule (responseByContentType?, defaultResponse?)>
<!ELEMENT responseByContentType (transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT defaultResponse (transform? | dispatch? | redirect? | forward?)>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT use EMPTY>
<!ATTLIST use
bean CDATA #IMPLIED
ticket CDATA #IMPLIED
>

<!ELEMENT translet (ticket*, request?, contents?, response?, transform?, dispatch?, redirect?, forward?, exception?)>
<!ATTLIST translet
path ID #REQUIRED
>

<!ELEMENT request (ticket*, attributes?, multiparts?)>
<!ATTLIST request
method CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>

<!ELEMENT properties (item*)>

<!ELEMENT arguments (item*)>

<!ELEMENT parameters (item*)>

<!ELEMENT item (#PCDATA | value | reference | null)*>
<!ATTLIST item
name CDATA #IMPLIED
value CDATA #IMPLIED
type CDATA #IMPLIED
valueType CDATA #IMPLIED
defaultValue CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA | reference | null)*>
<!ATTLIST value
name CDATA #IMPLIED
tokenize (true | false) #IMPLIED
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
bean CDATA #IMPLIED
parameter CDATA #IMPLIED
attribute CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT null EMPTY>

<!ELEMENT multiparts (fileItem*)>

<!ELEMENT fileItem (allowFileExtentions? | denyFileExtentions?)>
<!ATTLIST fileItem
name CDATA #REQUIRED
>

<!ELEMENT allowFileExtentions (#PCDATA)>
<!ELEMENT denyFileExtentions (#PCDATA)>

<!ELEMENT contents (content*)>

<!ELEMENT content (echo? | action? | include?)*>
<!ATTLIST content
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | item | value | null)*>
<!ATTLIST echo
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
id CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT include (attributes?)>
<!ATTLIST include
id CDATA #IMPLIED
path CDATA #REQUIRED
ignoreTicket (true | false) #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT response (ticket? | transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST response
characterEncoding CDATA #IMPLIED
default CDATA #IMPLIED
>
<!ELEMENT exception (responseByContentType?, defaultResponse?)>

<!ELEMENT transform (echo | action | include | template)*>
<!ATTLIST transform
id CDATA #IMPLIED
type CDATA #REQUIRED
contentType CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
encoding CDATA #IMPLIED
noCache (true | false) #IMPLIED
>

<!ELEMENT dispatch (echo? | action? | include? | target)*>
<!ATTLIST dispatch
id CDATA #IMPLIED
contentType CDATA #IMPLIED
>
<!ELEMENT target EMPTY>
<!ATTLIST target
path CDATA #REQUIRED
>

<!ELEMENT redirect (echo* | action* | include* | url? | parameters*)>
<!ATTLIST redirect
id CDATA #IMPLIED
contentType CDATA #IMPLIED
url CDATA #IMPLIED
path CDATA #IMPLIED
excludeNullParameters CDATA #IMPLIED
>
<!ELEMENT url (#PCDATA)>

<!ELEMENT forward (echo* | action* | include* | parameters*)>
<!ATTLIST forward
id CDATA #IMPLIED
contentType CDATA #IMPLIED
path CDATA #IMPLIED
>

=== aspectran-projects/aspectran/trunk/aspectran-web/config/aspectran/bak/exception-rule.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE translets PUBLIC "-//JHLabs.org//DTD Translets 1.0//EN"
                           "./dtd/translets-1.0.dtd">

<translets>

	<settings>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableBeanId" value="false"/>
	</settings>

	<typeAliases>
		<typeAlias alias="TestTicket" type="org.jhlabs.translets.test.TestTicket"/>
	</typeAliases>

	<bean id="a1" class="org.jhlabs.translets.test.TestBean" scope="singleton" factoryMethod="" initMethod="" destoryMethod="" lazyInit="false" >
		<features>
			<class>f</class>
			<scope>singleton</scope>
			<factoryMethod>aaa</factoryMethod>
			<initMethod></initMethod>
			<destroyMethod></destroyMethod>
			<lazyInit>false</lazyInit>
		</features>
		<constructor>
			<arguments>
				<item>string</item>
				<item type="list" valueType="int">
					<value>1</value>
					<value>2</value>
					<value>3</value>
				</item>
				<item type="map" valueType="string">
					<value name="aa"></value>
				</item>
			</arguments>
		</constructor>
		<properties>
			<item name="item" value="0" valueType="int"/>
			<item name="item0" valueType="int">0</item>
			<item name="item1">string</item>
			<item name="list1" type="list">
				<value>a</value>
				<value>b</value>
			</item>
			<item name="map1" type="map">
				<value name="key1">value</value>
				<value name="key2">value</value>
			</item>
			<item name="ref1">
				<reference bean="bean00"/>
			</item>
		</properties>
	</bean>

	<exceptionRule>
		<responseByContentType>
			<dispatch contentType="text/html">
				<view name="/WEB-INF/jsp/error.jsp"/>
			</dispatch>
			<!-- forward contentType="text/html" path="error"/ -->
			<transform contentType="text/plain" type="transform/text">
				<template>
					오류 발생!
					오류 발생!
				</template>
			</transform>
			<transform contentType="text/xml" type="transform/xml">
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
				<echo id="error3">
					<item name="code">0002</item>
					<item name="message">오류 발생!</item>
				</echo>
				<echo id="error1">
					<item type="map">
						<value name="code">0001</value>
						<value name="message">오류 발생!</value>
					</item>
				</echo>
				<echo id="error2">
					<item type="map">
						<value name="code">0002</value>
						<value name="message">오류 발생!</value>
					</item>
					<item type="map">
						<value name="code">0004</value>
						<value name="message">오류 발생!</value>
					</item>
				</echo>
			</transform>
		</responseByContentType>
		<defaultResponse>
			<redirect translet="error"/>
		</defaultResponse>
	</exceptionRule>

</translets>

=== aspectran-projects/aspectran/trunk/aspectran-web/config/aspectran/bak/root-translets.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE translets PUBLIC "-//JHLabs.org//DTD Translets 1.0//EN"
                           "./dtd/translets-1.0.dtd">

<translets>

	<settings>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
		<setting name="multiActivityEnable" value="true"/>
	</settings>

	<activityRule>
		<transletNamePattern>
			<prefix>/test/</prefix>
			<suffix>.do</suffix>
		</transletNamePattern>
		<description>
			근원이 되는 설정
		</description>
	</activityRule>

	<ticketRule>
		<checkcase id="loginCheck" rejectInvalidTicket="true" checkpoint="request">
			<action bean="common.ticket.t1" method="check">
				<arguments>
					<item name="stmtId">aaaaaaa</item>
				</arguments>
			</action>
			<responseByContentType>
				<dispatch contentType="text/html">
					<view name="/WEB-INF/jsp/error.jsp"/>
				</dispatch>
			</responseByContentType>
			<defaultResponse>
				<redirect translet="login"/>
			</defaultResponse>
		</checkcase>
		<checkcase id="loginFailed" rejectInvalidTicket="true">
			<action bean="common.ticket.t1"/>
			<responseByContentType>
				<dispatch contentType="text/html">
					<view name="/WEB-INF/jsp/error.jsp"/>
				</dispatch>
			</responseByContentType>
		</checkcase>
	</ticketRule>
	
	<requestRule>
		<characterEncoding>utf-8</characterEncoding>
		<multipart>
			<maxRequestSize>10M</maxRequestSize>
			<temporaryFilePath>/d:/</temporaryFilePath>
		</multipart>
	</requestRule>

	<responseRule>
		<characterEncoding>utf-8</characterEncoding>
		<defaultContentType>text/html</defaultContentType>
		<dispatcherViews default="jsp">
			<viewType id="jsp" class="org.jhlabs.translets.web.JspViewDispatcher"/> 
			<viewType id="tiles2" bean=""/> 
			<viewType id="other">com.abs.view</viewType> 
		</dispatcherViews>
	</responseRule>

	<exceptionRule>
		<responseByContentType>
			<dispatch contentType="text/html">
				<view name="/WEB-INF/jsp/error.jsp"/>
			</dispatch>
			<!-- forward contentType="text/html" translet="error"/ -->
			<transform contentType="text/plain" type="transform/text">
				<template>
					오류 발생!
					오류 발생!
				</template>
			</transform>
			<transform contentType="text/xml" type="transform/xml">
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
				<echo id="error3">
					<item name="code">0002</item>
					<item name="message">오류 발생!</item>
				</echo>
				<echo id="error1">
					<item type="map">
						<value name="code">0001</value>
						<value name="message">오류 발생!</value>
					</item>
				</echo>
				<echo id="error2">
					<item type="map">
						<value name="code">0002</value>
						<value name="message">오류 발생!</value>
					</item>
					<item type="map">
						<value name="code">0004</value>
						<value name="message">오류 발생!</value>
					</item>
				</echo>
			</transform>
		</responseByContentType>
		<defaultResponse>
			<redirect translet="error"/>
		</defaultResponse>
	</exceptionRule>

	<import resource="ticket-rule.xml"/>
	<import resource="exception-rule.xml"/>
	<import resource="front-translets.xml"/>
	<import resource="ajax-translets.xml"/>
</translets>
